### ISSUE TITLE
Can't open application after disconnecting extended display

### ISSUE THREAD

**Issue by alex37529** [r0x0r/pywebview#1229] opened 2023-10-02 13:52 UTC
### Specification
- pywebview version: 4.4.3
- operating system: Windows 11
- web renderer:

### Description

  In Windows 11 if use setup with two displays need a place pywebview application at display N2 in full screen mode and then disconnect display N2. Then application moved in full screen mode to display N1.   After exit from full screen mode application jumped to disabled monitor and makes unavailable.

### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment] 2023-10-04 09:44
The issue is fixed in master. Fullscreen window is now also opened to the current, instead of the primary monitor.

**Closed by r0x0r** 2023-10-04 09:44 UTC
