### ISSUE TITLE
Can i combine pyqt5 and pywebview and put pywebview inside a widget for example?

### ISSUE THREAD

**Issue by hippylover** [r0x0r/pywebview#236] opened 2018-06-11 20:03 UTC
Hi, im having problems with qtwebengine not working in virtualenv of one of my users. Iv'e had problems with this before. Can i perhaps replace qtwebengine with pywebview and put it inside a QtWidget or something?

Also, im wondering if i will get similar problems inside a virtualenv that i get with qtwebengine after reading something about this on the frontpage.

**Comment by r0x0r** [comment] 2018-06-12 08:01
Sorry, I don't quite follow what you are trying to achieve. If you have problems installing qtwebengine, why don't you give GTK a try?

**Comment by shivaprsdv** [comment] 2018-06-12 19:08
Seems like this is a duplicate of #206. @hippylover Can you check it out and
comment? If it is not what you are looking for, then you might need to explain
a bit more of what you are trying to achieve.

**Closed** 2018-08-12 11:43 UTC
Labels: linux, need more info, question
