### ISSUE TITLE
Deadlock while closing the window with persistent threads running

### ISSUE THREAD

**Issue by pomplesiegel** [r0x0r/pywebview#138] opened 2017-10-12 16:13 UTC
When updating the DOM from a separate thread, using calls like `webview.evaluate_js()` I found it quite useful to have an API call which indicates whether the window is still present / attempting to close.

### Problem
If one clicks the close button on a window (rather than quitting it like with Apple + Q), and then a separate thread calls to the webview object, like `webview.evaluate_js()`, this thread becomes blocked and stuck in that call indefinitely. 

What would be helpful is a function like
`webview.window_exists()`

which returns a boolean, which is set within `WindowDelegate::windowWillClose_()` (and the equivalent location on other platforms). I tested this by adding a global variable to cocoa.py which is set within `windowWillClose_`, and having `webview` return the status of this boolean. Certainly not the cleanest way, but it works. 

Could we perhaps integrate this in a more OO-friendly fashion. I'm happy to help.

Alternatively, we could provide an API for a  callback function, which would be called (in addition to the window closing) when the user hits the "x" or close button on a window. A sort-of cleanup call, to prevent deadlock. 

Thoughts?
Thanks!
Michael

**Comment by shivaprsdv** [comment] 2017-10-14 19:11
Hm, looks like this is an issue we should solve internally, rather than exposing
it to the API. `pywebview` already handles calls that occur _before_ the window is
created; the same could be done for calls that occur _after_. Another way is to
really _quit_ the app once the window is closed, just as if ⌘Q was pressed.

I think the cleanup-call feature is more plausible, especially in the later context.
This would be an addition to the already implemented confirm_quit parameter.
Thanks for the suggestion, I'll look into it and get back to you. 🙂 

BTW to check if the app is still running on Cocoa, you can use the [`isRunning()`](https://developer.apple.com/documentation/appkit/nsapplication/1428759-running?language=objc)
method of `BrowserView.app`, not need to keep a global variable.

**Comment by pomplesiegel** [comment] 2017-10-15 18:45
That would be great. Any thoughts of the equivalent call for WinForms?

**Comment by shivaprsdv** [comment] 2017-10-15 18:54
Roman does all Windows coding so I don't know much about it :) Nevertheless,
there doesn't seem to be an easy built-in way for this on WinForms; a global var
should be the best option.

**Comment by r0x0r** [comment] 2017-10-18 10:27
The deadlock must certainly be fixed, but I don't feel there is a need for a public window_exists function (unless multi-window functionality materializes). A better approach would be to catch windowWillClose/OnDestroy/etc event on each platform and a set a semaphore there, evaluate_js would acquire the semaphore and would check for the existence of the window before executing javascript code.

**Comment by shivaprsdv** [comment] 2017-10-18 10:48
I just noticed, in its current shape, the multi-window code automatically handles
this. The `get_instance` method there raises an exception if the user calls an API
on a non-existent window, which breaks the deadlock.

**Comment by pomplesiegel** [comment] 2017-10-25 15:30
@shivaprsdv, Any thoughts on the best path forward for this one? I have a single-window application, but should I use the multi-window branch simply for this behavior? Currently there is no elegant way to quit a program with persistent threads running.

**Comment by shivaprsdv** [comment] 2017-10-26 11:40
I have confirmed that we have indeed hit a bug here. This occurs on all platforms
I have tested. A patch for Cocoa is up, could get some help with testing.

@pomplesiegel Feel free to experiment with the `multi-window` branch as well.
Even if your app is single-window, it should not incur any overheads. I wrote that
code, with input from Roman and others; it is still in testing, so any feedback is
well appreciated. 🙂

**Comment by pomplesiegel** [comment] 2017-10-26 15:14
Great, i'll give the multi-window a shot. Thanks!

**Comment by pomplesiegel** [comment] 2017-10-27 16:13
@shivaprsdv, I just tested your branch "deadlock-fix" and it fixed my thread problem for quitting the program! Great work.

**Comment by shivaprsdv** [comment] 2017-10-28 11:00
Great, thanks. 🙂

But I should say it's likely to be only a temporary fix. For the problem seems to
be of a much general nature, and warrants a more solid, cross-platform solution.
We'll keep this issue open and updated.

**Comment by r0x0r** [comment] 2017-10-31 22:24
I have pushed a similar solution for WinForms to the deadlock-fix branch. Good to merge?

**Comment by shivaprsdv** [comment] 2017-11-01 04:08
Don't think so; we haven't had a solution to the problem on Linux.

Moreover, I don't think this approach would fix it for sure. I'm studying it in
detail, will report as soon as I can.

**Comment by shivaprsdv** [comment] 2017-11-01 08:39
Okay, I have pin-pointed the issue. It is two fold:
1. We are allowing API functions to be called even after closing the webview.
2. If the webview is suddenly closed, with a semaphore acquired from one of
the subthreads, it might not always get released.

Ideally, such calls should be blocked in the init file itself. This benefits all the
platforms, and would be compatible with the work on multi-window as well.

Keeping this in mind, I have redone the work on this issue: you can find it in
the deadlock-fix-alt branch. I've also added a tentative commit for Winforms
based on your last commit, feel free to amend it.

**Comment by pomplesiegel** [comment] 2017-11-01 16:21
@shivaprsdv, great. so far this is working well on Mac. Any reason not to expose `is_running()` to the public API? I see it as being helpful as a check for a thread before it attempts to call a webview function.

**Comment by shivaprsdv** [comment] 2017-11-01 17:04
Nothing particular. As I mention in the above commit message, `is_running`
could be removed in the future. But if you do want, simply follow the Python
[EAFP](https://docs.python.org/3/glossary.html#term-eafp) _(easier to ask for forgiveness than permission)_ principle:
```py
try:
    webview.evaluate_js()
    # webview is running
except:
    # webview is not running
```

**Comment by pomplesiegel** [comment] 2017-11-02 15:14
Great, that's what I'm doing now. Thanks!

**Comment by shivaprsdv** [comment] 2017-11-06 04:14
@pomplesiegel Can you test the `deadlock-fix` and `deadlock-fix-alt` branches on
Windows and tell us if they solve the issue? Thanks.

**Comment by r0x0r** [comment] 2017-11-15 18:49
@shivaprsdv Looks good. Would you make a PR?

**Closed** 2017-11-17 11:38 UTC
Labels: bug, linux, mac

**Comment by gitillusion09** [comment] 2024-07-20 07:57
Hello :) I am sorry to open this issue again, but I think the fix does not work (anymore ?) on Windows. When closing, the app keeps hanging forever. I have a render thread that in some cases, calls the evaluate_js method periodically. If the application closes at this exact moment, and even though the thread has been joined, the app keeps hanging forever. Does anyone have the issue on Windows?
