### ISSUE TITLE
Scrolling stops when scrolling a big list.

### ISSUE THREAD

**Issue by 0x410c** [r0x0r/pywebview#30] opened 2016-04-17 20:43 UTC
I have created a div with overflow-y:auto; which creates a scroll in div, when extra elements are there in that div,

Problem is, the scroll stops in between when you scroll up or down.

I am on Mac Os x el capitan.

Between Awesome work, thanks

**Comment by r0x0r** [comment] 2016-04-17 20:46
Could you provide an example html file?

**Comment by 0x410c** [comment] 2016-04-18 07:42
https://jsfiddle.net/1bbnzhvv/

try this, on mac osx el capitan, python 2.7

**Comment by r0x0r** [comment] 2016-04-18 11:47
I could not reproduce it on El Capitan. Can scroll up and down just fine. Can you provide more information?
<img width="1051" alt="screen shot 2016-04-18 at 14 43 46" src="https://cloud.githubusercontent.com/assets/1549657/14603076/5c794808-0574-11e6-819e-0e4ebf119e2b.png">

**Comment by 0x410c** [comment] 2016-04-18 14:00
scroll continuously to the top, or bottom starting from bottom or top, while continuously scrolling, it will stop

**Comment by r0x0r** [comment] 2016-04-20 07:07
Still no luck reproducing it. Please test it with Safari and see if it persists there.

**Comment by r0x0r** [comment] 2016-04-27 07:13
Is this still relevant?

**Comment by r0x0r** [comment] 2016-05-11 21:48
Closing as there have been no updates for over two weeks

**Closed** 2016-05-11 21:47 UTC
