### ISSUE TITLE
Need pywebview to start minimized

### ISSUE THREAD

**Issue by abhieee23** [r0x0r/pywebview#245] opened 2018-08-22 12:50 UTC
### Specification
- Platform: MacOS High Sierra
- Version: 2.0.3

### Description
Need pywebview window to start minimized. Cannot find a way to do it.

**Comment by romansirokov** [comment] 2018-08-23 07:10
You cannot do that in the current implementation. Could be implemented as a `minimized=False` parameter to `create_window` if you want to give it a shot.

**Comment by r0x0r** [comment] 2018-08-23 07:12
You cannot do that in the current implementation. Could be implemented as a minimized=False parameter to create_window if you want to give it a shot.

**Comment by baldyeagle** [comment] 2018-10-02 02:28
I can work on this, but I'll likely need help with QT and GTK3.

**Comment by r0x0r** [comment] 2018-10-02 06:49
Sure.
I have created a scaffold for the feature in the `minimized` branch

**Comment by shivaprsdv** [comment] 2018-12-22 06:14
I hope the title should be read as _Need pywebview to start **hidden**_ and not
_minimized_? Because minimizing has a very different effect on platforms like
macOS where it is accompanied by animation, and starting an app like that
is completely bewildering (I tested the PR by @baldyeagle).

> My use case for this would be to complete the initial loading and set up
before displaying the content to the user.

@mikaelho In case you are loading a resource-heavy app, it would be better
to show a loading indicator and do the set-up in the background, as shown
in `examples/loading_animation.py`. For currently, there is no callback API
available to signal to you that the loading has completed.

**Comment by adbenitez** [comment] 2019-08-07 17:39
agree with @shivaprsdv, but if:

> the title should be read as _Need pywebview to start **hidden**_ and not
> _minimized_

then this could be considered a duplicate of #253

**Comment by shivaprsdv** [comment] 2019-08-22 15:34
I think the OP of that issue was asking for a `window.hide()` function. BTW
implementing that would resolve this issue as well.

**Closed** 2019-10-28 08:37 UTC
Labels: all platforms, enhancement, good first issue
