### ISSUE TITLE
Strange focus behaviour

### ISSUE THREAD

**Issue by FeralFox** [r0x0r/pywebview#865] opened 2022-02-27 13:56 UTC
### Specification
- pywebview version: 3.6.1
- operating system: Windows
- web renderer: edgechromium

### Description  
  
Hello,
I have an issue when changing the focus of a window for the first time.
I have created a video [here](https://easyupload.io/igawc4) which is available until March, 27th.

Description:
Given I have a page with two text inputs.
When I run it and put the focus in the second text input
And I press Alt-Tab (or unfocus the window using the mouse)
And I re-focus the window again
Then the focus will be set to the first element.

My expectation would be, that the second element is focused again.
This is only "broken" for the first time. When I again set the focus to the second element, unfocus and re-focus the window again, then the second element will be focused as expected.

So my question would be: Is there something I can do to workaround this? I tried to call <secondinput>.focus() twice but it did not help. Setting "autofocus" on that element also didn't help. Only thing which comes into my mind is making an element with "tabindex=99999" which is created when the window is unfocused and when focused it focuses the previously active element.
  
Hint: When I set "cef" as renderer, the focus is not restored at all. Unfocusing the window will unfocus the active element. Refocusing the window will not emit a focusin event at all.

Minimal example with focus tracker:

```
import webview


class Api:
    def write(self, *args):
        print(''.join(args))

html = """
<body>
<input type="text" value="bla"></input>
<input id="haha" type="text" value="blubb"></input>
</body>
<script type="text/javascript">

window.addEventListener('focus', function(event) {
    pywebview.api.write(`FOCUSIN ${event.target.value} ${document.hasFocus()}`)
})
window.addEventListener('focusout', function(event) {
    pywebview.api.write(`FOCUSOUT ${event.target.value} ${document.hasFocus()}`)
})
</script>"""

window = webview.create_window('b', js_api=Api(), html=html, width=200, height=200)

webview.start(gui="cef")
```

### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment] 2022-02-28 21:28
I could not reproduce this problem with edge chromium, focus works as expected here. As for CEF, I pushed a fix for this to master.

**Closed** 2022-03-01 18:31 UTC
