### ISSUE TITLE
Save Dialog Not Working - Even Not In save_file_dialog.py Example - on macOS

### ISSUE THREAD

**Issue by SurfChriz** [r0x0r/pywebview#578] opened 2020-07-24 09:45 UTC
### Specification
- pywebview version: 3.3.1 (but have seen the issue in older versions as well)
- platform / version: macOS 10.15.6, Python 3.7.3

### Description  
  
When executing window.create_file_dialog(webview.SAVE_DIALOG....), the program stops execution and never delivers a result for that call.

I stumbled over the issue in a personal project and narrowed it down to not being able to execute the save_file_dialog.py example with the expected result.
Since it worked previously I suspected the macOS updates being the reason. So I started analysing by using the mac console.app, which brought up two errors when I executed the line of code in question:

1. `[NSOpenPanel filenames]: unrecognized (NSOpenPanel) selector sent to instance 0x7f865687c3a0.  This sandboxed application's NSSavePanel class object only responds to NSSavePanel APIs!  Please use the interface as described in NSSavePanel.h.`
2. (
	0   CoreFoundation                      0x00007fff36a16b57 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6f85d5bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff36a3f34c -[NSException raise] + 9
	3   _objc.cpython-37m-darwin.so         0x000000010b8a59de PyObjCErr_ToObjCWithGILState + 46
	4   _objc.cpython-37m-darwin.so         0x000000010b883333 method_stub + 5395
	5   _objc.cpython-37m-darwin.so         0x000000010b8a5364 ffi_closure_unix64_inner + 708
	6   _objc.cpython-37m-darwin.so         0x000000010b8a4886 ffi_closure_unix64 + 70
	7   CoreFoundation                      0x00007fff3699ad52 \_\_CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION\_\_ + 17
	8   CoreFoundation                      0x00007fff3699acf1 __CFRunLoopDoSource0 + 103
	9   CoreFoundation                      0x00007fff3699ab0b __CFRunLoopDoSources0 + 209
	10  CoreFoundation                      0x00007fff3699983a __CFRunLoopRun + 927
	11  CoreFoundation                      0x00007fff36998e3e CFRunLoopRunSpecific + 462
	12  HIToolbox                           0x00007fff355c5abd RunCurrentEventLoopInMode + 292
	13  HIToolbox                           0x00007fff355c57d5 ReceiveNextEventCommon + 584
	14  HIToolbox                           0x00007fff355c5579 _BlockUntilNextEventMatchingListInModeWithFilter + 64
	15  AppKit                              0x00007fff33c0b039 _DPSNextEvent + 883
	16  AppKit                              0x00007fff33c09880 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
	17  AppKit                              0x00007fff33bfb58e -[NSApplication run] + 658
	18  _objc.cpython-37m-darwin.so         0x000000010b8a4707 ffi_call_unix64 + 79
	19  ???                                 0x000000010e2c8ac8 0x0 + 4532767432
)

This looks like some security sandbox issues to me, but I am not pretty familiar with native mac development...

### Practicalities

- I am not willing to work on this issue myself.
- I am not prepared to support this issue financially.

**Comment by r0x0r** [comment] 2020-07-24 09:51
I cannot reproduce it with save_file_dialog example. 10.5.4 / pywebview master.

**Comment by SurfChriz** [comment] 2020-07-24 14:41
You mean macOS 10.5.4? That would underline the idea of having a macOS issue with recent updates.
I remember, that it worked roughly a year ago, so probably on 10.14.x. Probably due to the enhanced System Integrity Protection... But I am only guessing...

**Comment by r0x0r** [comment] 2020-07-30 08:36
Fixed in master now.

**Comment by r0x0r** [comment] 2020-08-08 09:31
Released in 3.3.3

**Closed by r0x0r** 2020-08-08 09:31 UTC
