### ISSUE TITLE
GTK crashes on window show

### ISSUE THREAD

**Issue by astronouth7303** [r0x0r/pywebview#514] opened 2020-05-10 19:02 UTC
### Specification
- pywebview version: master
- platform / version: PyGObject 3.36.1

### Description  
  
While working on #513, I found a GTK crashing bug that I don't think is my fault.

```
🐚 python examples/hide_window.py
Window is started hidden
Showing window
Bail out! Gtk:ERROR:../../../../gtk/gtkicontheme.c:4305:proxy_symbolic_pixbuf_destroy: assertion failed: (symbolic_cache != NULL)
**
Gtk:ERROR:../../../../gtk/gtkicontheme.c:4305:proxy_symbolic_pixbuf_destroy: assertion failed: (symbolic_cache != NULL)
Aborted (core dumped)
```
  
### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment] 2020-05-11 21:07
Could not reproduce this with PyGObject 3.20. Will try again with 3.36 as soon as I figure how to install it.

**Comment by r0x0r** [comment] 2020-05-11 21:15
Ok both fail with PyGObject 3.36. Will look into this.

**Comment by astronouth7303** [comment] 2020-05-11 22:59
ok, debian testing:

```
libgtk-3-0/testing,now 3.24.18-1 amd64 [installed,automatic]
libgtk-3-bin/testing,now 3.24.18-1 amd64 [installed,automatic]
libgtk-3-common/testing,testing,now 3.24.18-1 all [installed,automatic]
libwebkit2gtk-4.0-37/testing,now 2.28.2-2 amd64 [installed,automatic]
```

**Comment by r0x0r** [comment] 2020-05-26 20:57
Fixed on master

**Closed by r0x0r** 2020-05-26 20:57 UTC
