### ISSUE TITLE
Promises sometimes don't get called

### ISSUE THREAD

**Issue by rotu** [r0x0r/pywebview#390] opened 2019-10-08 23:40 UTC
### Specification
- pywebview version: 3.0.2
- platform / version: MacOS Catalina

### Description  
  
Initiate a function call from python to javascript multiple times. Observe that the function does get called multiple times but only one value is returned to Javascript via promise.

```javascript
    for (let i = 0; i < 10; i++) {
        console.log('request ' + i);
        api.echo(i).then((j) => {
            console.log('response ' + i)
        })
    }
```
```python
class JSApi:
    def echo(self, value):
        print(value)
        return value
```

Javascript output:
```
[Log] request 0 (main.js, line 39)
[Log] request 1 (main.js, line 39)
[Log] request 2 (main.js, line 39)
[Log] request 3 (main.js, line 39)
[Log] request 4 (main.js, line 39)
[Log] request 5 (main.js, line 39)
[Log] request 6 (main.js, line 39)
[Log] request 7 (main.js, line 39)
[Log] request 8 (main.js, line 39)
[Log] request 9 (main.js, line 39)
[Log] response 0 (main.js, line 41)
```
  
### Practicalities

- YES I am willing to work on this issue myself.

- NO I am not prepared to support this issue financially.

**Comment by r0x0r** [comment] 2019-10-09 08:14
It looks like a race condition is in question here. As a function level global return value is used, it gets immediately overwritten by subsequent function calls. A solution would be to differentiate function calls by uuid or something along these lines.

**Comment by rotu** [comment] 2019-10-09 17:45
I wouldn’t call it a race condition but you’re spot on about the cause. I’m actively working on a fix.

**Comment by r0x0r** [comment] 2019-10-15 20:58
I have pushed a tentative fix to the `js-api-fix` branch. It is mostly untested, tests should be fixed and Windows binaries should be regenerated as well.

**Comment by r0x0r** [comment] 2019-10-16 19:37
PR here
https://github.com/r0x0r/pywebview/pull/400

**Comment by r0x0r** [comment] 2019-10-23 07:39
`test_js_api::test_concurrent` randomly fails on Windows. After hours of debugging I could not track the cause of the bug down. I won't spend any more time trying to fix it and let it be for the time being. Let's hope it is a bug in the `assert_js` and not the underlying code.

**Closed** 2019-10-23 07:39 UTC
