### ISSUE TITLE
Managing Focus For Accessibility

### ISSUE THREAD

**Issue by mush42** [r0x0r/pywebview#836] opened 2021-12-23 22:28 UTC
### Specification

- pywebview version: 3.5
- operating system: Windows 10 64-bit
- web renderer: Edge

### Description  
  
I'm trying to integrate pywebview with blindpandas/bookworm to provide some extra services.
 
 Bookworm targets blind people who use a screen reader to interact with their computer. Screen reader users rely on the keyboard to navigate the apps.
 
 While the embedded  browser component in pywebview is fully accessible, there are some focus issues with pywebview that prevents a screen reader user from interacting with the app. Those issues are:
 
 1. PyWebview does not set focus to the embedded browser control when the window is focused. The user cannot use the tab key to set focus to the browser neither.
 2. If the user clicked on the browser control using the mouse the focus is set to the browser control, but the focus will be lost if the user switched away and back to the pywebview app from another app. Note that using the mouse is not an option for blind people.
 3. When the browser control is focused the user cannot use Alt+F4 to close the pywebview app

>  Using pywebview==3.5, Python 3.9.9 64-bit on Windows 64 bit with [the latest version of the free screen reader NVDA](https://nvaccess.org/)

  
### Practicalities

- I not willing to work on this issue myself because I lack the pertinent experience in this area. But I'll appreciate any guidance. And I'm ready to test any fix and give feedback.

- I am not prepared to support this issue financially. Practically, I'm a team of one who provide this app free of charge.
Best Regards,

**Comment by r0x0r** [comment] 2022-01-03 22:13
I have pushed a tentative fix into `win-focus` branch. It covers three MS renderers, but not CEF. 
I have no means of testing it, so please test if it fixes your problems.

I could not reproduce no. 3, but I tested with Edge Chromium. EdgeHTML is not worth fixing.

**Comment by mush42** [comment] 2022-01-09 01:36
Hi,

The problem seams to be partially fixed.

Testing with mshtml, the focus to web content is not set automatically upon page load, but if you switched away and back to the window the focus is set to the web content, but not reliably ( sometimes it is set sometimes not).

Regards,

**Comment by r0x0r** [comment] 2022-01-29 22:28
To be honest I don't know how to test if focus is set correctly. I have verified that focus methods are called, no idea why focus might not be set.
Is MSHTML relevant to you? It is deprecated and I have no interest in supporting it.

**Comment by r0x0r** [comment] 2022-02-16 15:09
Focus fixes are released in 3.6. I am closing this. Feel free to reopen if you find any more information.

**Closed by r0x0r** 2022-02-16 15:09 UTC
