### ISSUE TITLE
the 'master' problem

### ISSUE THREAD

**Issue by fordffx** [r0x0r/pywebview#230] opened 2018-05-24 16:23 UTC
### Specification
- Platform:win7 64bit
- Version:pywebview2.03

### Description
my code:
Popentable_tag=False 
...
if Popentable_tag==False :
--t = threading.Thread(target=htmlto.loadhtml,name='tablewindow')
--t.start()
--Popentable_tag=True
api=htmlto.mjs_api()
webview.create_window('tata', js_api=api)

the first time i saw my 'tata' window, and i closed it.  but  when the second time i run the code ,error flash out:
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/untitled/temp.py", line 781, in <module>
    main()
  File "C:/Users/Administrator/PycharmProjects/untitled/temp.py", line 725, in main
     webview.create_window('tata', js_api=api)
  File "C:\ProgramData\Anaconda3\lib\site-packages\webview\__init__.py", line 183, in create_window
    background_color, debug, js_api, text_select, _webview_ready)
  File "C:\ProgramData\Anaconda3\lib\site-packages\webview\winforms.py", line 252, in create_window
    BrowserView.instances['master'].Invoke(Func[Type](create))
KeyError: 'master'

please help ,thanks!
i think define a window.on_close->stop a thread thing may help ,but how?

**Comment by r0x0r** [comment] 2018-05-24 16:35
Duplicate of #229

**Comment by r0x0r** [comment] 2018-05-24 18:57
Check the `issue229-fix` branch for a quick fix. 
I am closing this issue now

**Closed by r0x0r** 2018-05-24 18:57 UTC
Labels: duplicate
