### ISSUE TITLE
webview crashes when showing an image

### ISSUE THREAD

**Issue by alfem** [r0x0r/pywebview#32] opened 2016-05-20 09:52 UTC
I am testing pywebview in order to make a simple digital signage application.

Webview shows most of the urls ok (even youtube fullscreen videos!), but when I give it a jpg or png url (local or http), a Segmentation Fault error comes out.

I am using ubuntu 14.04.

**Comment by r0x0r** [comment] 2016-05-29 21:44
I could not reproduce it. Both JPG and PNG, QT and GTK worked for me. 14.04 LTS, default Python installation.
```
webview.create_window("", "https://upload.wikimedia.org/wikipedia/commons/b/b4/JPEG_example_JPG_RIP_100.jpg")
webview.create_window("", "http://orig02.deviantart.net/533b/f/2015/161/a/e/itunes_13_icon__png__ico__icns__by_loinik-d8wqjzr.png")
```

Can you check whether you use QT or GTK and which version?

**Comment by alfem** [comment] 2016-05-30 06:35
I have got installed libqtwebkit4:i386  (2.3.2-0ubuntu7), libqt5webkit5:i386 (5.1.1-1ubuntu8), and  libwebkitgtk-3.0-0:i386 (2.4.8-1ubuntu1~ubuntu)

Tested with both, qt and gtk.

**Comment by alfem** [comment] 2016-05-30 08:27
My simple digital signage app is here https://github.com/alfem/carrousel

It fails in different installations of Ubuntu 14.04 LTS. In some of them I get a Segfault with images, and others just jumps on some pages. I think is a matter of webkit, not your library.

**Comment by r0x0r** [comment] 2016-06-08 20:32
Closing this.

**Closed by r0x0r** 2016-06-08 20:32 UTC
