### ISSUE TITLE
http server shutdown when call load_url

### ISSUE THREAD

**Issue by overflow** [r0x0r/pywebview#442] opened 2019-12-06 04:55 UTC
### Specification
- pywebview version:  3.1
- platform / version: gtk

### Description  
 Why the http server is shutdown when load_url is called?
  
### Practicalities

- YES/NO I am willing to work on this issue myself.
NO
- YES/NO I am prepared to support this issue financially.
NO

**Comment by r0x0r** [comment] 2019-12-06 10:29
To avoid resource leaking. 
When navigating to different URL, http server is no longer needed and thus shutdown. If the new url is local, when a new instance of http server is started. Ideally it should check if the new url is in the same directory as the old url to avoid server restart, but it is not implemented yet.

**Comment by overflow** [comment] 2019-12-06 12:55
but If I load a new URL the http server is always  shutdown, so can this condition can be true?
```
     if self._httpd:
            self._httpd.shutdown()
            self._httpd = None

        url = transform_url(url)

        if (self._httpd or self.gui.renderer == 'edgehtml') and url.startswith('file://'):
            url, self._httpd = start_server(url)
```

**Comment by r0x0r** [comment] 2019-12-12 08:32
This is clearly a bug. I pushed a fix to the master branch, now it should work as intended.

**Closed** 2019-12-15 21:13 UTC
