### ISSUE TITLE
Support for Blink

### ISSUE THREAD

**Issue by jhillhouse92** [r0x0r/pywebview#387] opened 2019-10-03 20:10 UTC
### Specification
- pywebview version: latest
- platform / version: MacOS

### Description  
Chromium / Chrome changed render engines to Blink a while ago, a fork from Webkit. Is it possible to enable one to choose the render engine and add support for Blink (it looks like that if OS is Mac, then it forces Webkit)?

**Comment by r0x0r** [comment] 2019-10-03 20:20
I have no idea. Investigate plz.

**Comment by jhillhouse92** [comment] 2019-10-03 20:53
Seems like there is CEF Python (chromium embedded framework), but that seems to be a complete alternative to pywebview (with a much less intuitive API). From Chromium's website, "Blink is implemented on top of an abstract platform and thus cannot be run by itself. The Chromium Content module provides the implementation of this abstract platform required for running Blink." So unless pywebview included CEF and wrapped it with a consistent API as its on WebView, doesn't look like Blink can be supported.

**Comment by r0x0r** [comment] 2019-10-04 07:04
As a matter of fact, pywebview supports CEF already, but on Windows only. I made CEF implementation generic enough (`platforms/cef.py`), so incorporating other platforms should not be too difficult task. Here is an example how CEF code can be incorporated into a Cocoa application https://bitbucket.org/chromiumembedded/cef/src/master/tests/cefsimple/cefsimple_mac.mm?at=master

`platforms/winforms.py` provides an example how platform code interacts with CEF. The glue code is a bunch of if's, a better architecture would be welcomed.

**Comment by r0x0r** [comment] 2019-10-29 13:20
Duplicate of #15

**Closed by r0x0r** 2019-10-29 13:20 UTC
