### ISSUE TITLE
pywebview doesn't always size it's content correctly at startup under windows

### ISSUE THREAD

**Issue by jonathon-love** [r0x0r/pywebview#11] opened 2015-10-26 11:30 UTC
hi,

when i first launch my application, the content isn't sized correctly to begin with. about 20 pixels are outside the view port to the right and to the bottom. if you look at the following screenshot, you can see a line of pixels at the right belonging to the scrollbar which is mostly outside the view port.

<img width="510" alt="screen shot 2015-10-26 at 12 21 36 pm" src="https://cloud.githubusercontent.com/assets/3240247/10727767/a189c9da-7bdc-11e5-92d3-1d35b29e9507.png">

if i resize the window just slightly, by a single pixel, it resizes the content to the viewport correctly. see this next screenshot.

<img width="504" alt="screen shot 2015-10-26 at 12 21 47 pm" src="https://cloud.githubusercontent.com/assets/3240247/10727785/c86287fe-7bdc-11e5-92ee-5dc5381b788e.png">

i appreciate this may be a bug in upstream, i.e. in the activex control container (or whatever you use), but perhaps this could be worked around by sending a resize message to the control after it is made visible? just a thought. (i always get annoyed when people who have no idea how my software works, make suggestions for how i can fix things; so i probably shouldn't make these suggestions :P )

once again, thank you for all your work on pywebview!

jonathon

**Comment by r0x0r** [comment] 2015-10-26 17:52
Does the problem persist if you specify different window dimensions?
Anyhow, could you provide this HTML file? A saved static webpage with
styles would suffice. I suspect it might be a problem with styles.

**Comment by jonathon-love** [comment] 2015-10-26 18:21
> Does the problem persist if you specify different window dimensions?

yup.

> Anyhow, could you provide this HTML file? A saved static webpage with styles would suffice. I suspect it might be a problem with styles.

the following html (i.e. any html) has the same issue. running under windows 8

    <!DOCTYPE html>
    <html>
    <head>
    </head>
    <body>
    <p>moo</p>
    <p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p><p>moo</p>
    <p>moo</p><p>moo</p>
    </body>
    <html>

<img width="375" alt="screen shot 2015-10-26 at 7 16 57 pm" src="https://cloud.githubusercontent.com/assets/3240247/10738225/9f8127b6-7c16-11e5-842c-3ba791dc1e0b.png">
<img width="378" alt="screen shot 2015-10-26 at 7 17 10 pm" src="https://cloud.githubusercontent.com/assets/3240247/10738236/a3299eac-7c16-11e5-8fea-a184c04f7223.png">
thanks for your time!

**Comment by r0x0r** [comment] 2015-10-26 21:46
The problem lied in the fact that the size of the browser container did not take scrollbars into account. I just pushed a fix. Would you mind testing it? I will create a new release after verifying that the problem is gone.

**Comment by jonathon-love** [comment] 2015-10-26 21:47
awesome! thanks for your time.

so to test it, do i need to compile it from source? and does that require Visual C? (because i don't have that).

**Comment by r0x0r** [comment] 2015-10-26 21:51
Pull the code from here and place the webview folder under your project folder. Then import webview in Python and you should be set.

**Comment by jonathon-love** [comment] 2015-10-26 21:54
yup! works a treat.

thanks so much.

**Comment by r0x0r** [comment] 2015-10-26 21:55
Thanks to you. I am closing this issue.

**Closed by r0x0r** 2015-10-26 21:55 UTC
