### ISSUE TITLE
Weird Exceptions When Running Window().destroy()

### ISSUE THREAD

**Issue by gabbarreiro** [r0x0r/pywebview#705] opened 2021-03-03 19:58 UTC
### Specification
- pywebview version: 3.4
- operating system: Linux Mint 19.1 Cinnamon (kernel 4.15.0-20-generic) x86_64
- web renderer: gtk?

### Description  
 
When one window triggers some code that pops a second window and I try to destroy that second window it's printed the following exception:

```Traceback (most recent call last):
  File "/home/gabriel/.local/lib/python3.6/site-packages/webview/platforms/gtk.py", line 374, in _callback
    self.js_results[unique_id]['result'] = value.get_js_value().to_string()
KeyError: 'c772879e7c5911eba095681401f000f5'
```
Despite the exception, it sucessfully closes the window. But then when I close the application more exceptions pops on the screen before it closes:

```Traceback (most recent call last):
  File "/home/gabriel/.local/lib/python3.6/site-packages/webview/platforms/gtk.py", line 191, in on_webview_ready
NameError: name 'dir' is not defined
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
ImportError: sys.meta_path is None, Python is likely shutting down

Original exception was:
Traceback (most recent call last):
  File "/home/gabriel/.local/lib/python3.6/site-packages/webview/platforms/gtk.py", line 191, in on_webview_ready
NameError: name 'dir' is not defined
Traceback (most recent call last):
  File "/home/gabriel/.local/lib/python3.6/site-packages/webview/platforms/gtk.py", line 191, in on_webview_ready
NameError: name 'dir' is not defined
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
ImportError: sys.meta_path is None, Python is likely shutting down

Original exception was:
Traceback (most recent call last):
  File "/home/gabriel/.local/lib/python3.6/site-packages/webview/platforms/gtk.py", line 191, in on_webview_ready
NameError: name 'dir' is not defined
```

In my computer the error occur when running [this](https://gist.github.com/gabbarreiro/626faafafc91a324da956aab7a8951e0l) code.

### Practicalities

- YES/NO I am willing to work on this issue myself.
NO
- YES/NO I am prepared to support this issue financially.
YES

**Comment by r0x0r** [comment] 2021-03-06 10:39
Could you post a minimal example that would reproduce the problem?

**Comment by gabbarreiro** [comment] 2021-03-10 01:24
I've linked it in my first post. The link for the gist is here: https://gist.github.com/gabbarreiro/626faafafc91a324da956aab7a8951e0l

**Comment by r0x0r** [comment] 2021-03-23 21:59
I pushed a fix to master. This problem was caused by releasing a JS result semaphore when closing a window before it could obtain result of the js code telling the window to close.

**Closed by r0x0r** 2021-03-23 21:59 UTC
