### ISSUE TITLE
Can't open a new window from the JS API

### ISSUE THREAD

**Issue by TheInitializer** [r0x0r/pywebview#229] opened 2018-05-20 22:29 UTC
### Specification
- Platform: winforms
- Version: 2.0.3

### Description
My code looks a bit like this:

```
import os
import threading

import webview


class FirstWindowApi:
    def on_button(self):
        webview.destroy_window()
        t = threading.Thread(target=create_second_window)
        t.start()


class SecondWindowApi:
    pass


def create_second_window():
    second_window = webview.create_window("Window 2", os.path.abspath("web\\window2.html"), js_api=SecondWindowApi)



first_window = webview.create_window("Window 1", os.path.abspath("web\\window1.html"), js_api=FirstWindowApi)
```

However, when I click the button, it crashes with this exception:

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "ui_pywebview.py", line 23, in create_second_window
    second_window = webview.create_window("Window 2", os.path.abspath("web\\window2.html"), js_api=SecondWindowApi)
  File "C:\Program Files\Python36\lib\site-packages\webview\__init__.py", line 183, in create_window
    background_color, debug, js_api, text_select, _webview_ready)
  File "C:\Program Files\Python36\lib\site-packages\webview\winforms.py", line 252, in create_window
    BrowserView.instances['master'].Invoke(Func[Type](create))
KeyError: 'master'
```

**Comment by shivaprsdv** [comment] 2018-05-21 06:25
@r0x0r I think this is a bug in our code, always calling `Invoke` on the `master`
while it could have been destroyed, as it happened for the OP. I have tried on a
quick fix, pushed to 1ef00f9539f6b247f04f8b0b317e889d9ddeb71c. @TheInitializer Can you check if it is working? I
don't have Windows. 🙂

**Comment by shivaprsdv** [comment] 2018-05-21 10:15
Agree. The app closing on last-window-close was just for the time being, in
want of a better model. So the behaviour we intent, if I understand correctly,
would be to give back the control we block on the first call to `create_window`,
right?

**Comment by TheInitializer** [comment] 2018-05-22 20:52
@shivaprsdv I tried it and it works, if I don't destroy the window beforehand. If I do, it gives me this error:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\webview\__init__.py", line 132, in wrapper
    return function(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\webview\__init__.py", line 286, in evaluate_js
    return gui.evaluate_js(escaped_script, uid)
  File "C:\Program Files\Python36\lib\site-packages\webview\winforms.py", line 375, in evaluate_js
    window = BrowserView.instances[uid]
KeyError: 'master'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python36\lib\site-packages\webview\__init__.py", line 315, in _call
    evaluate_js(code, uid)
  File "C:\Program Files\Python36\lib\site-packages\webview\__init__.py", line 141, in wrapper
    raise Exception('Cannot call function: No webview exists with uid: {}'.format(uid))
Exception: Cannot call function: No webview exists with uid: master
```

(I can live with this problem - I can just tell my users to close the window beforehand.)

**Comment by TheInitializer** [comment] 2018-05-23 00:33
it also works if I destroy the window within the second window's thread, which works fine for me.

**Comment by shivaprsdv** [comment] 2018-05-23 06:26
This time it is the expected behaviour. This is the proper exception pywebview
raises if you try to call any api function on a non-existent window, as mentioned
in our README:

> In all cases, uid is the uid of the target window returned by create_window();
if no window exists with the given uid, an exception is thrown.

Just wrap your code within a `try-except` block and handle it yourself. Better
than forcing your users to do something. 🙂 

@r0x0r It seems my patch fixes _this_ issue. Can we merge it to master? Let us
open a new issue for tracking the app-termination-behaviour.

**Comment by r0x0r** [comment] 2018-05-24 19:01
I pushed a fix to the `issue229-fix` branch that at least fixes the problem I described.
@TheInitializer I think it won't solve your issue, but could you give it a test just in case?

**Comment by r0x0r** [comment] 2018-05-24 20:16
Changed Cocoa so that it does not terminate the app on the window close. Multi-window tests are currently failing.

**Comment by r0x0r** [comment] 2018-05-24 20:47
I sporadically get a WebKit Threading Violation with multi_window.py. 

```
2018-05-24 23:34:49.812 Python[90347:13486107] WebKit Threading Violation - initial use of WebKit from a secondary thread.
2018-05-24 23:34:50.071 Python[90347:13486106] !!! BUG: The current event queue and the main event queue are not the same. Events will not be handled correctly. This is probably because _TSGetMainThread was called for the first time off the main thread.
2018-05-24 23:34:50.076 Python[90347:13486106] pid(90347)/euid(211155011) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
```

No clue what causes it. @shivaprsdv any ideas?

**Comment by shivaprsdv** [comment] 2018-05-25 03:37
Yes, this occurs when you create an instance of WebKit for the first time from
a non-main thread. Any such call was being blocked in `create_window()` in
`__init__.py` itself. Do you get this with the current `master`? I hope it occurs
with the quick fix you applied?

I don't think quick-fixes would do to solve the root problem. We need a well
planned and well designed revamp of window-creation logic.

**Comment by r0x0r** [comment] 2018-05-25 09:18
@TheInitializer looking at your code again, I realized it won't work due the limitations of underlying GUIs. Namely that the GUI loop must be launched on the main thread. Since you destroy the main window and thus end the application loop, creating a new window must take place on the main thread. 

What you can do though, is to refactor your code to create a new window before destroying the main one. You don't need to spawn a new thread, as the on_button code takes place in a separate thread and `create_window` is not blocked.

**Comment by r0x0r** [comment] 2018-05-25 10:00
WebKit threading issues are fixed and tests pass now (on OSX at least). This should solve all the issues, but more thorough testing is in order.

**Comment by TheInitializer** [comment] 2018-05-25 17:47
@r0x0r i've figured out a solution that works. I create a new thread, start another window from the new thread, then destroy the old window (also from the new thread).

**Comment by TheInitializer** [comment] 2018-05-25 18:45
(i'm having another issue related to this, will try the `issue229-fix` branch)

**Comment by fordffx** [comment] 2018-05-28 14:14
@r0x0r   @TheInitializer 
class DownThread:
    def __init__(self):
        self._running = True

    def terminate(self):
        self._running = False

    def run(self, n):
        while self._running and n > 0:
            print('T-minus', n)
            n -= 1
            time.sleep(5)

c = DownThread()
t = Thread(target=c.run, args=(10,))
t.start()
c.terminate() 
t.join()      
#==============
import multiprocessing
c = DownThread(5)
p = multiprocessing.Process(target=c.run)
p.start()

# I think this may help，use  multiprocessing。

**Comment by TheInitializer** [comment] 2018-05-29 17:49
@r0x0r maybe there should be a way to keep the main thread running, using an infinite loop or something, so that I can open new windows?

**Comment by r0x0r** [comment] 2018-05-30 11:16
@TheInitializer as your case could be solved by switching the order of destroy_window and create_window, I see no reason in keeping application loop alive. Besides how would you terminate the application loop if a keep-alive feature would be implemented?

The threading model should be probably be documented in README.

**Comment by r0x0r** [comment] 2018-05-31 20:04
QT had the same problem as Windows with restarting application loop. All the platforms should be fixed by now.

**Comment by fordffx** [comment] 2018-06-01 12:56
@r0x0r I think it would be better if webview handling logic and thread handling logic are seperated.

**Comment by r0x0r** [comment] 2018-06-03 16:48
@fordffx Could you elaborate?

**Comment by shivaprsdv** [comment] 2018-06-03 18:13
@r0x0r I have pushed some improvements to application-loop restart on Cocoa.

**Closed** 2018-06-07 12:16 UTC
Labels: all platforms, bug
