### ISSUE TITLE
When written as a sample, webview.load_html() is sometimes called before the webview is ready.

### ISSUE THREAD

**Issue by TakamiChie** [r0x0r/pywebview#320] opened 2019-03-22 11:24 UTC
### Specification
- Platform: Windows 10 1809 Build 17763.379
- Version: 2.4(Rendering Engine: Trident)

### Description
A sample of the load_html() described in [sample page](https://github.com/r0x0r/pywebview/blob/master/examples/load_html.py) is written as follows.

```py
def load_html():
    webview.load_html('<h1>This is dynamically loaded HTML</h1>')

if __name__ == '__main__':
    t = threading.Thread(target=load_html)
    t.start()

    webview.create_window('Load HTML Example')
```

However, in this case, in a low-spec PC environment, such as the Atom CPU, webview#load_html() is invoked before WebView is ready and may cause an error.

As follows, it seems that it is desirable to perform the ready waiting for WebView.

```py
def load_html():
    webview.webview_ready()
    webview.load_html('<h1>This is dynamically loaded HTML</h1>')

if __name__ == '__main__':
    t = threading.Thread(target=load_html)
    t.start()

    webview.create_window('Load HTML Example')
```

### What to expect.

The program works in many environments by writing it as shown in the sample.

**Comment by shivaprsdv** [comment] 2019-03-22 15:40
All API [internally wait](https://github.com/r0x0r/pywebview/blob/master/webview/__init__.py#L182) for Webview before firing, which is what `webview_ready()`
solely does as well. So I don't see why it needs to be invoked separately. This
function was introduced so that users can wait for the WebView before doing
something _other than_ API calls and still needed to ensure the webview is ready.

> However, in this case, in a low-spec PC environment, such as the Atom CPU,
webview#load_html() is invoked before WebView is ready and may cause an
error.

We are yet to encounter such a bug. Is it only a speculation? If not, can you give
the steps-to-reproduce?

**Comment by TakamiChie** [comment] 2019-03-23 16:46
You are currently using PyWebView in the following applications:
[TakamiChie/Re\-VIEW\-Preview: Tool to live Preview any Re:VIEW format document](https://github.com/TakamiChie/Re-VIEW-Preview/blob/master/LICENSE)

On this application, it was confirmed that the following error comes out in the middle probability when the application starts.

```
Cannot call function: No webview exists with uid: pos
  File "D:\Users\takamichie\documents\dev\review_preview\.venv\Lib\site-packages\webview\__init__.py", line 192, in wrapper
    raise Exception('Cannot call function: No webview exists with uid: {}'.format(uid))
  File "D:\Users\takamichie\documents\dev\review_preview\src\js_api.py", line 120, in show_review
    pos = webview.evaluate_js("pos")
  File "D:\Users\takamichie\documents\dev\review_preview\src\js_api.py", line 44, in on_modified
    self.owner.show_review()
  File "D:\Users\takamichie\documents\dev\review_preview\.venv\Lib\site-packages\watchdog\events.py", line 330, in dispatch
    _method_map[event_type](event)
  File "D:\Users\takamichie\documents\dev\review_preview\.venv\Lib\site-packages\watchdog\observers\api.py", line 368, in dispatch_events
    handler.dispatch(event)
  File "D:\Users\takamichie\documents\dev\review_preview\.venv\Lib\site-packages\watchdog\observers\api.py", line 201, in run
    continue
  File "C:\Python36\Lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Python36\Lib\threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
```

After confirming the reproduction, it was confirmed that the same problem goes out in the `webview# evaluate_js().`

This error is no longer in the process of waiting for the `load_html()` method to start, such as `webview.webview_ready()` or `time.sleep()`. It is determined that there is a case where the processing has been done before the WebView is ready.

> We are yet to encounter such a bug. Is it only a speculation? If not, can you give
> the steps-to-reproduce?

### Environment confirming reproduction

The present event is confirmed by the following PC at present.

* GPD Pocket
  * CPU: Atom x7
  * Memory: 8GB
  * ERROR Incidence: 5 attempts and 5 times
* Lenovo V520-15IKL
  * CPU: Core i5-7500
  * Memory: 32GB
  * ERROR Incidence: 10 attempts and 4 occurrences

### Reproduction procedure

1. Create a static HTML file
2. Sample street, `threading.Thread()` is used to invoke the threads in order to load the above files into WebView.
3. Immediately, invoke the `webview.create_window()` method to display the WebView.

The corresponding line on the application is as follows:

* https://github.com/TakamiChie/Re-VIEW-Preview/blob/33de5f516ec6c93cfe3f3c28719efd208ddd851c/src/main.py#L32

**Comment by r0x0r** [comment] 2019-03-25 07:40
@TakamiChie 
There is a timeout of 5 seconds in `_js_api_call` https://github.com/r0x0r/pywebview/blob/097c3067da79672ec3972806fb73ea68472aedfe/webview/__init__.py#L182
If the window is not created within five seconds, then the lock will be released and a call will most likely fail. The reason why this timeout exists is to allow windows to fail, instead of stalling into an infinite limbo. 
As for a resolution, could you increase this limit to let's say 10 seconds and see if it solves your problems?

**Comment by TakamiChie** [comment] 2019-03-29 15:23
When I tried to edit the above line, the error certainly no longer occurred.

```python
        try:
            _webview_ready.wait(10)
            return function(*args, **kwargs)
        except NameError:
            raise Exception('Create a web view window first, before invoking this function')
        except KeyError as e:
```
* pywebview/WebView/__init__.py Pre-edited: tried to start 20 times and four times the error.
* After editing: 20 attempts to start and without error.

Also, running the application in GPD Pocket, the error is no longer occur, it is considered to have been sufficiently effective.

**Comment by r0x0r** [comment] 2019-04-05 20:51
I have changed the timeout to 15 seconds and made it to throw a separate exception if the window is not opened by then. Closing this.

**Closed by r0x0r** 2019-04-05 20:51 UTC
Labels: need more info, windows
