### ISSUE TITLE
Make winforms DPI aware for high resolution screens

### ISSUE THREAD

**Issue by tango293** [r0x0r/pywebview#87] opened 2017-02-27 22:53 UTC
On my Microsoft SurfaceBook my app looks blurry, I think because I have a high-resolution screen. Is it possible to modify the winforms wrapper to account for this? I think it has to do with the AutoScaleMode property of the windows form, and a .NET "DPIAware" setting, as described here: http://crsouza.com/2015/04/13/how-to-fix-blurry-windows-forms-windows-in-high-dpi-settings/

If this could be fixed, apps made with pywebview would look a lot better on hi-res Windows screens. Thanks!

**Comment by r0x0r** [comment] 2017-02-28 21:03
I have applied the recipe described in this form, but I am not sure what it should look like. Could you test it yourself and tell if it makes it less blurry? The code is in the master branch.

**Comment by tango293** [comment] 2017-02-28 22:36
Thanks for your quick response! I think that's a step in the right direction. What happens now is that the text is nice and clear, but it has also shrunk. I'll attach screenshots before and after applying your change. 

After the change, I can zoom in on the app (e.g. Ctrl-+), and it looks good. As the text sizes up, it remains sharp. So as a workaround, that is okay, but it is still an extra step that users with high-def screens will have to take.

Note that if I open this html file in Firefox or Edge, it appears at the proper size and sharp. So there is still something that browsers are doing but pywebview isn't.

This is the line in my python file:
`webview.create_window("Simple browser", width=800, height=600, resizable=True)`


**BEFORE (proper size, but fuzzy):**
![before](https://cloud.githubusercontent.com/assets/26073784/23437153/4bea434e-fdca-11e6-8b1a-42991799b045.png)

**AFTER (sharp, but too small):**
![after](https://cloud.githubusercontent.com/assets/26073784/23437154/4bebb94a-fdca-11e6-9293-07f02142cdd4.png)

**Comment by tango293** [comment] 2017-03-01 00:02
I think this would be helpful: https://msdn.microsoft.com/en-us/library/ms229605(v=vs.110).aspx
I'm afraid I'm in way over my head though.

**Comment by r0x0r** [comment] 2017-03-02 11:30
I am a bit lost as well. I have tried playing with different AutoScale* settings, but to no avail. What I have noticed though, if you don't have meta viewport set in your index.html, it won't shrink html elements. The window will stay small though, so 800x600 will look tiny

**Comment by r0x0r** [comment] 2017-03-05 09:43
I have added appropriate AutoScaleDimensions, it should look fine now. Please test the latest master and report back if it solves the problem for you.

**Comment by tango293** [comment] 2017-03-05 17:01
Thanks. What happens now is that the windows is the correct size, but the content is still too small. If you just load some raw html (e.g. using your "load_http.py" script), the content is the right size. But when loading a normal webpage, the content is small. Here is a screenshot of github.com, for example, in an 800x600 window. 

![sketch](https://cloud.githubusercontent.com/assets/26073784/23589439/5653438a-018a-11e7-96d4-e0ad7aa3d2f2.png)

I've also tried commenting out the meta viewport settings in my index.html, but that doesn't seem to make a difference.

**Comment by r0x0r** [comment] 2017-03-07 07:54
This seems to be a solution to the DPI problem (Enabling HDPI Support to the WebOC)
https://msdn.microsoft.com/en-us/library/mt622670.aspx

I have tried applying it, but could not get past casting a COM interface on a .NET object in pythonnet. Any help on how this can be done is appreciated.

**Comment by r0x0r** [comment] 2017-03-24 21:47
I have moved the auto-scale code out of master to the winforms-dpi-fix branch for now.

**Comment by denfromufa** [comment] 2017-04-25 03:51
@r0x0r .NET 4.7 comes with high dpi support for winforms:

https://docs.microsoft.com/en-us/dotnet/articles/framework/winforms/high-dpi-support-in-windows-forms

**Comment by r0x0r** [comment] 2017-04-26 17:26
@denfromufa, that's excellent news! The article mentions making changes to a manifest file. If I understand correctly, they should be added to Python.Runtime.dll. Is this correct?

**Comment by r0x0r** [comment] 2017-09-18 22:02
Looks like the most feasible solution would be to move unmanaged code into its own assembly and ship pywebview with a prebuilt DLL. I will look into it when I get a chance.

**Comment by pomplesiegel** [comment] 2017-10-11 17:51
👍 It would be really fantastic to have this render on high DPI screens in windows. I have a 4k screen at my desktop, and the current look is quite blurry.

**Comment by pomplesiegel** [comment] 2017-10-18 15:35
@r0x0r, any thoughts on what it would take to resolve this? Perhaps I can help? This would be a big win for Windows users.

**Comment by r0x0r** [comment] 2017-10-20 10:31
@pomplesiegel Are you familiar with .NET/Win32 programming?

It has been more than half a year since I tackled this, so memories are hazy, but the work I have done can be found here https://github.com/r0x0r/pywebview/commit/0eadcf2ab9a962d2612e76b230fc4e662cd1c0e9

The problem is that there is no way I am aware of to cast an object to a COM interface in pythonnet (lines 89-92 in the commit above). To solve this I propose to create a DLL with a bridge to COM interfaces we need and load it as an assembly in Python code. Here is an example how it can be done in C#
https://www.codeproject.com/Articles/2491/Using-MSHTML-Advanced-Hosting-Interfaces
This is the basic idea, sorry for the lack of details.

I have been busy with other stuff lately, so this might take a while for me to give this proper effort.

**Comment by r0x0r** [comment] 2017-10-24 21:49
Right, I've made some progress on this issue. I've compiled COM interfaces into an assembly, which can now be loaded and successfully referenced from Python. The code for the DPI fix stuff is in place, but alas it results in a crush in the compiled DLL. I am not sure whether the problem lies with how DLL is compiled or with how interfaces are handled from the Python side. My bet is on the former. Help would be greatly appreciated.
Current work can be found here https://github.com/r0x0r/pywebview/tree/winforms-dpi-fix

**Comment by pomplesiegel** [comment] 2017-10-25 15:28
Thanks for looking into this! I'll take a look as well. Unfortunately I have very limited experience with .NET/Win32 programming outside of making standalone apps in Visual studio, but i'll take a look.

**Comment by r0x0r** [comment] 2018-01-25 15:56
Right, I got it working somehow, but not sure if it fixes the problem. At least GetHostInfo of IDocHostUIHandler is called and sets appropriate flags. @pomplesiegel @tango293 would you test it? The `winforms-dpi-fix` branch has the fix. In my limited testing I noticed that a click on the webview window content is required to get GetHostInfo called. This is something to keep in mind at this point.

**Comment by r0x0r** [comment] 2018-02-20 20:09
Should be working now. I merged the fix with the master.

**Closed by r0x0r** 2018-02-20 20:09 UTC
Labels: good first issue, help wanted, windows

**Comment by tango293** [comment] 2018-02-21 05:08
Works beautifully! Thanks!
