### ISSUE TITLE
Is there a way to create a window on custom location?

### ISSUE THREAD

**Issue by acbetter** [r0x0r/pywebview#356] opened 2019-07-27 07:44 UTC
I want to create a window at the center or somewhere of my screen, is there a way to do that?

```python
webview.create_window(title, url='', html='', js_api=None, width=800, height=600, x=1000, y=1000)
# x,y is the top left location of window in my screen
```

https://github.com/r0x0r/pywebview/blob/f76b02831434ad62fe22073b66ec40f303f0e8d0/webview/platforms/cocoa.py#L419-L421

**Comment by r0x0r** [comment] 2019-07-27 08:29
No, but if anyone to tackle this, you are most welcome.
Also a duplicate of #351.

**Closed** 2019-07-28 13:21 UTC
